stages:
  - build
  - deploy

variables:
  NODE_ENV: production

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - cd /aicounter/web_fe_dev
    - npm install
    - npm run build

deploy:
  stage: deploy
  script:
    - cp -r /aicounter/web_fe_dev/build/* /aicounter/web_fe/public
    - zip -r release.zip *
  only:
    - main
