rtsp:
  base_url: rtsp://localhost:8554/ai/
yolo:
  model: jv_indo_m_320.engine
  allowed_cls:
    - mobil
    - motor
    - bus
    - truck
    - bus besar
    - truck besar
mqtt:
  host: localhost
  base_topic_pub: cam_log
ws:
  host: ws://localhost:8080/
  host2: ws://localhost:8081/
smp:
  - name: mobil
    smp: 1
  - name: motor
    smp: 0.5
  - name: bus
    smp: 3
  - name: truck
    smp: 3
  - name: bus besar
    smp: 3
  - name: truck besar
    smp: 3
presence_detector:
  active: true
  id: 1
  fase: 1
  mqtt:
    host: localhost
    username: javis
    password: '#MqttJavis313'
    topic:
      send: 'its-link/server/'
      receive: 'its-link/client/'
  mode: gap # ds / gap
  threshold: 0.5
